<html lang="en">
<?php include '../includes/head.inc.php'; ?>
<body>
	<?php include '../includes/header.inc.php'; ?>
	<div class="container">
		<div class="row">
	        <div class="col-xs-12">
	          <div class="blog-post">
        <h1>Car Cooling System</h1>
        		<p class="lead"><a href="car_cooling_system.pdf">Download</a> a PDF of the reading.</p>
	          <h3>Learning Objectives</h3>
	          <ul class="objectives">
					<li>Students should be able to list the essential functions of a car's cooling system</li>
					<li>Students should be able to describe how the cooling system decreases the freezing point and increases the boiling point of water.</li>
					<li>Students should be able to diagram how a radiator effectively lowers the temperature of coolant.</li>
					<li>Students should be able to describe how the thermostat controls the temperature of the coolant.</li>
					<li>Students should be able to describe the role of the heater core.</li>
					<li>Students should be able to diagram how the radiator cap regulates the pressure of coolant.</li>
				</ul>
				<h2>Introduction</h2>
				
				<p>In medical school you will spend a lot time studying systems: cardiovascular, respiratory, urinary, etc. For each of those systems, you will learn its major functions, study how the anatomical, tissue, cellular and molecular components generate those functions and then see how defects or damage to those components compromise those functions resulting in disease.</p>
				
				<p>In this session you will learn about a car's cooling system, which is a much simpler system than those you will study in medical school. Simpler, because it is a system that is designed and made by people and not one that has evolved over millions of years. Consequently, we understand how each of the components of our human-made system work and contribute to the functions of the system, whereas for the systems that composed the human body we are still discovering new components and learning how the known components work.</p>
				
				<h2>Functions</h2>
				
				<p>A car's cooling system serves two major functions. The most important function is to keep the car's engine block within a optimal range of temperatures. The engine block is where combustion of a gas-air mixture generates power to propel a car. Unfortunately, most of the energy of combustion is converted to heat which can cause the engine block to reach extremely high temperatures. So high, that without a cooling system the aluminum and metal components of the engine block would weld.</p>
				
				<p>Although its imperative that the cooling system prevent the temperature of the engine block from rising too high, engines are designed to operate most efficiently and cleanly at relatively high temperatures. Thus, the cooling system must allow a cold engine to reach quickly its optimal running temperature.</p>
				
				<p>The second function of the cooling system is to provide a source of heat for the passenger compartment.</p>
				
				<h2>Coolant</h2>
				
				<p>Most cars are liquid-cooled which means they use a water-based solution to absorb heat from the engine block. On its own, the physical properties of water are inadequate to be an effective coolant for the car engines. First, water becomes a solid at temperatures below 32&deg;  F, and anyone living in the Northeast during the winter knows that temperatures can remain below 32&deg; F for long periods of time. To decrease the freezing point of the coolant, water is mixed with ethylene glycol. A mixture of 50% water and 50% ethylene glycol remains a liquid to around -40&deg;  F.</p>
				<figure style="width:100%;">
					<object data ="coolant.svg" type="image/svg+xml"></object>
				</figure>
				
				<p>The second problem with water is that it becomes a gas at 212&deg;  F. Most engines are designed to operate at temperatures that heat coolant to 200&deg;  F with occasional spikes of near 250&deg;  F. To prevent the water in coolant from boiling, cooling systems keep the coolant under a pressure of 15 psi. The increased pressure raises the liquid-gas transition phase of the water to about 250&deg;  F. </p>
				
				<h2>Anatomy</h2>
				
				<p>All liquid-based cooling systems in cars comprise a set of essential parts. </p>
				
				<ul>
					<li>Radiator</li>
					<li>Water pump</li>
					<li>Thermostat</li>
					<li>Heater core</li>
				</ul>
				<figure style="width:100%;">
					<object data ="anatomy.svg" type="image/svg+xml"></object>
				</figure>
				
				<p>The radiator lowers the temperature of the coolant that comes from the engine block. After leaving the radiator, the coolant flows to the water pump which pushes the coolant into the engine block. As the coolant flows through the engine block, it absorbs the heat generated by combustion in the pistons. </p>
				
				<p>The cycling of the coolant between the radiator and engine block would be sufficient to prevent the engine from overheating, but it cannot fulfill two other features of the cooling system: allowing a cold engine to warm quickly and providing heat for the passenger compartment.</p>
				
				<p>The thermostat regulates the temperature of the coolant by controlling the direction the coolant flows after leaving the engine block. When the engine is cold the thermostat prevents the coolant from flowing to the radiator and instead, sends the coolant directly to the water pump and then back into the engine block. By bypassing the radiator, the heat of combustion rapidly increases the the temperature of the coolant allowing the engine block to reach its optimal operating temperature. Once the coolant reaches a minimal temperature (about 195&deg; F), the thermostat starts to divert coolant to the radiator.</p>
				
				<p>The last component of the cooling system is the heater core which provides a source of heat for the passenger compartment.</p>
				
				<p>To understand better how the cooling system works and how it often fails, we will look at a couple of components in more detail.</p>
				
				<h2>Radiator</h2>
				<figure style="width:100%;">
					<object data ="radiator.svg" type="image/svg+xml"></object>
				</figure>
				
				<p>The main function of the radiator is to dissipate the heat of the coolant coming from the engine block. In addition, the radiator also regulates the pressure of the coolant, maintaining a pressure of 15 psi. Most radiators are made of aluminum because of its high thermal conductivity. The radiator contains numerous aluminum tubes arranged in parallel. As the hot coolant enters the radiator, it flows through one of the tubes transferring its heat to the wall of the tube. Attached to outer wall of tubes are flattened aluminum fins. The fins enlarge the surface area, increasing the efficiency of heat dissipation from the tubes to the surrounding air. Air is blown across the fins either by a fan or when the car is in motion.</p>
				
				<h2>Radiator Cap</h2>
				<figure style="width:100%;">
					<object data ="radiator_cap.svg" type="image/svg+xml"></object>
				</figure>
				
				<p>On the top of the radiator is a cap that serves two functions. First, it seals an opening to the radiator where coolant can be added. More interestingly, the cap controls the pressure of the coolant. The coolant resides in a closed compartment (radiator, engine block and tubes connecting the two) with a constant volume. As the coolant heats up, its pressure increases because the volume of coolant is constant. To prevent the coolant pressure from rising too high (at which point it could leak into the combustion chamber of the pistons), the cap allows some of the coolant to escape at high pressure and flow into an external chamber. The seal on the cap that closes the opening of the radiator is attached to a spring. The force of the spring pushes the seal tightly onto the opening. When the pressure of the coolant rises to 15 psi, it generates enough force to compress the spring and lift the seal off the radiator opening. This allows a small amount of coolant to leave the radiator and flow through a diversion tube into an adjacent overflow chamber. When the engine is turned off and the coolant in the radiator cools, the decrease in pressure creates a vacuum to draw the coolant from the overflow chamber back into the radiator.</p>
				
				<h2>Thermostat</h2>
				<figure style="width:100%;">
					<object data ="thermostat.svg" type="image/svg+xml"></object>
				</figure>
				
				<p>The function of the thermostat is to regulate the temperature of the coolant by controlling the amount of coolant that flows from the engine block to either the radiator or back into the engine block. When the coolant is cold, the thermostat is closed causing all of the coolant from the engine block to bypass the radiator and return to the engine block. This allows the coolant to heat up quickly. When the coolant reaches a minimum temperature (about 195&deg;  F), the thermostat opens sending some of the coolant to the radiator.</p>
				
				<p>Similar to the radiator cap, the thermostat uses a spring and seal to close off the port leading to the radiator. The thermostat also contains a cylinder filled with wax. As the temperature of the coolant reaches 195&deg;  F, the wax begins to melt and expand in volume. The increased volume of wax pushes on the spring to open the port leading to the radiator while closing the port that allows coolant to recycle back into the engine block.</p>
				
				<h2>Heater core</h2>
				
				<p>On cold days, passengers can increase the temperature of the cabin by turning a dial or electronically increasing the temperature setting. These interfaces open a valve that allowing coolant to flow from the engine block into a small radiator, called the heater core, located underneath the dashboard. A fan blows the heat of the radiator core into the passenger compartment. Increasing the temperature setting in the cabin, diverts more coolant from the engine block into the heater core.</p>
				
				<h2>Conclusion</h2>
				
				<p>The cooling system contains few components but those components work together to keep the engine within a specified range of temperatures and provide a source of heat to passengers. Importantly, a defect in any one component will compromise the efficiency of the system leading to overheating of the engine.</p>



	          </div><!-- /.blog-post -->
	       </div><!--/.col-xs-12-->
		</div><!--/.row-->
    </div><!-- /.container -->
<?php include '../includes/scripts.inc.php'; ?>

</body></html>